### ISSUE TITLE
Submitting Attachments In Disconnected use

### ISSUE THREAD

**Issue by phuls** [Esri/geoform-template-js#106]
The attachment never submitted when coming back online, yet the point and data did just fine.

![image](https://cloud.githubusercontent.com/assets/6557827/3388245/d6406526-fc85-11e3-925a-7820c3ad4b90.png)

**Comment by driskull** [comment]
We are seem to be having problems with addAttachments in Geoforms. I
noticed the following was closed but we seem to be seeing the same
problem:

Here is some background (from one of our developers):

I'm still seeing a bug which has to do with Esri's offline geoforms not
supporting submitting attachments (at all, doesn't error out, just acts
like it doesn't even ever try to submit them). I've used the AGOL template
they have up, and pulled the latest fixed version today from github. Both
seem broken.  I did some browser tracing and think I have it pinned down
to precisely what the issue is...the updated version DOES now try to
addAttachments, but fails (throws "{"error":{"code":499,"message":"Token
Required","messageCode":"GWM_0003","details":["Token Required"]}}" error).
Specifically it's failing because it needs a token and for some reason
doesn't send one along with the request ONLY when the user hits the submit
button while offline.  If they submit while online, it sends the
addAttachments request with the token just fine.


Where is the problem:
There's only 2 relevant places where addAttachments is found in the
sourcecode,
js\main.js
js\vendor\offline\offline-edit-min.js
I suspect the issue lies in the offline-edit-min.js code somewhere
stemming off of the "_sendStoredAttachments" function at line 377
(unminified), but am not up to date enough with my coding skills anymore
to trace it out (especially on the minified version, original may be
easier).

**Comment by driskull** [comment]
@andygup any chance you might have an idea of what may be the issue?

**Comment by andygup** [comment]
@driskull not sure. I'm back in the office on Friday. Let's chat then to see about walking me thru the steps to reproduce. I'll need to run the app on my end to see if I can isolate the issue further.

**Comment by driskull** [comment]
awesome, thanks @andygup.

**Comment by driskull** [comment]
@andygup I was able to reproduce this using a hosted feature service that is not shared publicly. When going back online, it submits and sends a token for the feature but does not send a token for the attachment so it fails.

It seems like when going back online and submitting attachments, it needs to send a token along if necessary.

**Comment by andygup** [comment]
The fix can be tracked here: https://github.com/Esri/offline-editor-js/issues/286.

**Comment by andygup** [comment]
@driskull just following up on this and in case you aren't watching the offline-editor-js repo, v2.7 is available and it should fix https://github.com/Esri/offline-editor-js/issues/286.

**Comment by driskull** [comment]
thanks @andygup !
