### ISSUE TITLE
Datepicker format not working

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#418]
I switched month and day and it's not working.

**Comment by CTDisasterManagement** [comment]
@driskull 

We tried switching day, month, date and datepicker was working fine.
But if we use 'mm' for month instead of 'MM' then date picker will not work because 'mm' stands for minutes.
Can you provide the date format where date picker is not working, so we can test and get back to you?

Thanks!!

**Comment by driskull** [comment]
I'll send one soon. I just tried switching month and day order and it didn't work for me.

- Matt


On Feb 17, 2015, at 11:45 PM, CTDisasterManagement <notifications@github.com<mailto:notifications@github.com>> wrote:


@driskull<https://github.com/driskull>

We tried switching day, month, date and datepicker was working fine.
But if we use 'mm' for month instead of 'MM' then date picker will not work because 'mm' stands for minutes.
Can you provide the date format where date picker is not working, so we can test and get back to you?

Thanks!!

**Comment by driskull** [comment]
Verified this is working.

**Comment by CTDisasterManagement** [comment]
Thanks @driskull
