### ISSUE TITLE
RTL css should be after theme.css

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#421]
theme css files are messing up RTL mode. The RTL css should be loaded after theme.css so that it takes precedence.

**Comment by CTDisasterManagement** [comment]
@driskull 

This is with reference to #420.
If we move the logic of applying "rtl.css" in constructor(main.js) then first "rtl.css" will be loaded if required and then respective theme file will be loaded through "_switchStyle" function in "main.js"

Thanks!!

**Comment by CTDisasterManagement** [comment]
@driskull 

Issues #354 and #420 are related to each other.
The buttons were getting overlapped with each other because "rtl.css" was not getting applied in builder mode(code was moved from "constructor" to "startup" in "main.js").
So to resolve all three issues:
- We will move the code to apply "rtl.css" after "_switchStyle" function in "main.js" so RTL css will be applied after theme.css, this will resolve issue 421 and we can close 420.
- We will add the same line of code in author mode to apply the "rtl.css" in "startup" and this will resolve issue 354.

**Comment by driskull** [comment]
That sounds good. Thanks for looking  into them. I thought they might be related.

- Matt


On Feb 17, 2015, at 11:21 PM, CTDisasterManagement <notifications@github.com<mailto:notifications@github.com>> wrote:


@driskull<https://github.com/driskull>

Issues #354<https://github.com/Esri/geoform-template-js/issues/354> and #420<https://github.com/Esri/geoform-template-js/issues/420> are related to each other.
The buttons were getting overlapped with each other because "rtl.css" was not getting applied in builder mode(code was moved from "constructor" to "startup" in "main.js").
So to resolve all three issues:

  *   We will move the code to apply "rtl.css" after "_switchStyle" function in "main.js" so RTL css will be applied after theme.css, this will resolve issue 421 and we can close 420.
  *   We will add the same line of code in author mode to apply the "rtl.css" in "startup" and this will resolve issue 354.
