### ISSUE TITLE
Default values defined in feature template are not used when field is turned off

### ISSUE THREAD

**Issue by chris-fox** [Esri/geoform-template-js#506]
When a layer has a feature template with default values defined for fields and those fields are turned off it doesn't honor the default value. Values are being set to null in the feature that is created.

This seems similar to [#470](https://github.com/Esri/geoform-template-js/issues/470), but rather than default values defined for the field, they are defined on the feature template for the field.

This is important because it looks like the defaultValue property on hosted feature services fields is no longer supported. When you publish from ArcMap or Pro they are always set to null and they can't be set through the rest api either.

Issue [#90](https://github.com/Esri/geoform-template-js/issues/90) talks about adding support for using the value from the feature template and it does work properly if the field is displayed in the form. It is populated with the default value when the form is loaded. We are looking for this to also work when the field is not visible.

**Comment by driskull** [comment]
hey @chris-fox I believe we fixed this from another issue. I'll see if I can locate it.

Would you mind testing with the code from the development branch? it should work there.

**Comment by chris-fox** [comment]
@driskull, yes this is working as expected in the development branch, thanks. Will this be in the next release of online? We have a couple solutions that could really benefit from this functionality.

**Comment by driskull** [comment]
Yep! it will. It's already checked into the code for the next release.

Thanks for checking.

**Comment by tchristo** [comment]
Sorry but this particular option does not seem to be working for me. To reiterate @chris-fox original issue: I can set a default value in a feature template and if I show that field in geoform it honors the default value. But if I hide this field from geoform, it just goes to null (in the feature class) after submitting the form. The reason I'm running into this is because I'm using the same feature class for 2 different layers each with their own geoforms, so I can't set the default back at the fc-level.

**Comment by driskull** [comment]
This should be ok now in the development branch. As long as it has a default value defined in a feature template, it should work fine.

**Comment by tchristo** [comment]
Hi Matt,
I’m not sure what ‘development branch’ means but if I use the GeoForm builder on AGOL (and also publishing feature services from our own ArcGIS Server and not AGOL hosted feature layers), then the default value (from a feature template) for a field, hidden from geoform, will not show up in the feature class.
I can send screenshots if that will help but for now, I think I’ve managed to create a workaround by creating a new field with a default value on the fc and then just hide this field before publishing for the other layer, so that will just return null (instead of the wrong default value).
Treg
