### ISSUE TITLE
Where can I find the 'fields' options?

### ISSUE THREAD

**Issue by randomblink** [Esri/geoform-template-js#541]
I've seen the basic field options...
name, alias, fieldDescription, visible, typeField, tooltip, displayType

But in browsing and searching through the issues on this geoform I've also seen mention of an **editable** option and **nullable** and more.

Where would I find a list of these and their definitions?

**Comment by driskull** [comment]
nullable means the field is required, the service won't accept null values.

editable means the field is modifiable. 

They are from here: https://developers.arcgis.com/javascript/3/jsapi/field-amd.html

**Comment by randomblink** [comment]
When I add this in I am still able to edit the field. I was hoping for a means to lock the field. Make it visible to the end users and show them the selection from the domains but not allow them to select any.

**Comment by clm42** [comment]
You can make some edits to the code that will let you lock a field. I made one myself but it wouldn't let the user see the domain though. What it does is set the Bootstrap input property of the field to disabled which makes it grayed out and the user cannot interact with it at all though you can set its value from the code. You could edit the code so that the app ignores that field on submission which would let the user interact with it but not actually submit its value but that could cause confusion for the users because it looks like data is being lost.

**Comment by randomblink** [comment]
Thanks to some recent updates and new code for main.js (which I hope/believe is being added to the core) I can now lock the field which makes me happy as far as this request / issue.
